baseURL = "https://rosericazondekon.github.io/"
title = "Gbedegnon Roseric Azondekon"
theme = "gokarna"
languageCode = "en"
defaultContentLanguage = "en"
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = "G-3TBYJJHRP3"

# Choose one of emacs, trac or perldoc
pygmentsStyle = "monokai"

[params]
  footer = "Roseric Azondekon"
  description = "Public Health Informatics Specialist, Epidemiologist & Medical Entomologist"
  avatarURL = "https://rosericazondekon.github.io/blog/images/roz.webp"
  avatarSize = "size-m"
  customHeadHTML = """
    <!-- KaTeX -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.13.16/dist/katex.min.css" integrity="sha384-6LkG2wmY8FK9E0vU9OOr8UvLwsaqUg9SETfpq4uTCN1agNe8HRdE9ABlk+fVx6gZ" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.13.16/dist/katex.min.js" integrity="sha384-31El76TwmbHj4rF9DyLsygbq6xoIobG0W+jqXim+a3dU9W53tdH3A/ngRPxOzzaB" crossorigin="anonymous"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.13.16/dist/contrib/auto-render.min.js" integrity="sha384-vZTG03m+2yp6N6BNi5iM4rW4oIwk5DfcNdFfxkk9ZWpDriOkXX8voJBFrAO7MpVl" crossorigin="anonymous"
        onload="renderMathInElement(document.body);"></script>
  """
  socialIcons = [
    {name = "github", url = "https://github.com/rosericazondekon"},
    {name = "stackoverflow", url = "https://stackoverflow.com/users/9065044/roseric-azondekon"},
    {name = "twitter", url = "https://twitter.com/razondekon"},
    {name = "linkedin", url = "https://www.linkedin.com/in/roseric-azondekon-phd-mph-ms-a8385059"},
    #{name = "dribbble", url = "https://example.com"},
    #{name = "instagram", url = "https://example.com"},
    #{name = "twitch", url = "https://example.com"},
  ]
  metaKeywords = ["blog", "rosericazondekon", "gazondekon", "razondekon" "gbedegnon", "roseric", "azondekon"]

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 3

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4
  
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 5

  [[menu.main]]
    identifier = "github"
    pre = "<span data-feather='github'></span>"
    url = "https://github.com/rosericazondekon"
    weight = 6

  [[menu.main]]
    identifier = "buymeacoffee"
    pre = "<span data-feather='coffee'></span>"
    url = "https://www.buymeacoffee.com/gazondekon"
    weight = 7

  [[menu.main]]
    identifier = "rss"
    pre = "<span data-feather='rss'></span>"
    url = "/index.xml"
    weight = 8
